name: Code Quality CHeck and Pull Request To Test

on: 
  push:
    branches:
      - Dev

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run Flake8
      run: |
        flake8 --ignore=F405,F403,F401

  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          commit-message: Automatic PR to Test
          title: Automatic PR to Test
          body: Automatic PR to Test
          base: Test
          branch: Temp PR Branch
          delete-branch: true
