name: Code Quality CHeck and Pull Request To Test

on: 
  push:
    branches:
      - Dev

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run Flake8
      run: |
        flake8 --ignore=F405,F403,F401

  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      id: create_pr
      run: |
        # Replace these variables with your own values
        base_branch=Test  # Replace with the target branch
        head_branch=Dev  # Replace with the source branch
        title="Feature added to Dev. Test Time now"

        # Create a pull request using the GitHub API
        response=$(curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{
            "title": "'"$title"'",
            "body": "'"$body"'",
            "head": "'"$head_branch"'",
            "base": "'"$base_branch"'"
          }' \
          "https://api.github.com/repos/${{ github.repository }}/pulls")

        echo "Pull request created with response: $response"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
