name: Flake8 on Code.py

on:
  push:
    branches: 
      - Dev

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        
    - name: Run flake8 on Code.py
      run: |
        flake8 --ignore=F405,F403
